[package]
name = "shade-store"
description = "Shade SQLite store and refinery migrations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
r2d2.workspace = true
r2d2_sqlite.workspace = true
refinery.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
