//! mTLS configuration for the mesh.
//!
//! Both peers share the same trust root (the botnet CA generated by
//! `shade init-ca`). Each presents its own node cert (signed by that CA)
//! during the handshake. Server-side requires + verifies a client cert
//! before any application bytes flow.
//!
//! `cert_node_id` extracts the node identifier from a peer cert's
//! Subject CN. The handshake layer compares this to the `node_id`
//! advertised in `PeerHello` and drops the connection on mismatch — that
//! comparison is what binds transport identity to application identity.

use std::sync::Arc;

use rustls::pki_types::{CertificateDer, PrivateKeyDer};
use rustls::server::WebPkiClientVerifier;
use rustls::{ClientConfig, RootCertStore, ServerConfig};

/// Errors building TLS configurations.
#[derive(Debug, thiserror::Error)]
pub enum TlsConfigError {
    #[error("rustls error: {0}")]
    Rustls(#[from] rustls::Error),
    #[error("client verifier error: {0}")]
    ClientVerifier(#[from] rustls::server::VerifierBuilderError),
    #[error("CA bundle has no usable certificates")]
    EmptyCaBundle,
    #[error("CA bundle parse: {0}")]
    CaParse(String),
    #[error("certificate parse: {0}")]
    CertParse(String),
}

/// Build the rustls `ServerConfig` used by the mesh listener.
///
/// Requires + verifies a peer cert chain rooted at `ca_bundle`.
pub fn server_config(
    ca_bundle: Vec<CertificateDer<'static>>,
    cert_chain: Vec<CertificateDer<'static>>,
    key: PrivateKeyDer<'static>,
) -> Result<ServerConfig, TlsConfigError> {
    let roots = build_roots(ca_bundle)?;
    let verifier = WebPkiClientVerifier::builder(Arc::new(roots)).build()?;
    let cfg = ServerConfig::builder()
        .with_client_cert_verifier(verifier)
        .with_single_cert(cert_chain, key)?;
    Ok(cfg)
}

/// Build the rustls `ClientConfig` used by the mesh dialer. Verifies
/// the server cert chain rooted at `ca_bundle` and presents our own
/// node cert for the server's mutual-TLS check.
pub fn client_config(
    ca_bundle: Vec<CertificateDer<'static>>,
    cert_chain: Vec<CertificateDer<'static>>,
    key: PrivateKeyDer<'static>,
) -> Result<ClientConfig, TlsConfigError> {
    let roots = build_roots(ca_bundle)?;
    let cfg = ClientConfig::builder()
        .with_root_certificates(roots)
        .with_client_auth_cert(cert_chain, key)?;
    Ok(cfg)
}

fn build_roots(ca_bundle: Vec<CertificateDer<'static>>) -> Result<RootCertStore, TlsConfigError> {
    if ca_bundle.is_empty() {
        return Err(TlsConfigError::EmptyCaBundle);
    }
    let mut roots = RootCertStore::empty();
    for cert in ca_bundle {
        roots.add(cert)?;
    }
    Ok(roots)
}

/// Extract the node identifier from a peer cert.
///
/// Looks for the first DNS-name SAN; falls back to the Subject CN.
/// Returns `None` if the cert has neither (which means it wasn't issued
/// by `shade issue-cert` and shouldn't be talking to the mesh).
#[must_use]
pub fn cert_node_id(cert: &CertificateDer<'_>) -> Option<String> {
    let (_, parsed) = x509_parser::parse_x509_certificate(cert.as_ref()).ok()?;
    if let Ok(Some(san_ext)) = parsed.subject_alternative_name() {
        for name in &san_ext.value.general_names {
            if let x509_parser::extensions::GeneralName::DNSName(s) = name {
                return Some((*s).to_owned());
            }
        }
    }
    let cn = parsed
        .subject()
        .iter_common_name()
        .next()
        .and_then(|cn| cn.as_str().ok())
        .map(str::to_owned);
    cn
}

#[cfg(test)]
pub(crate) mod test_pki {
    //! Reusable rcgen scaffolding for tests in this crate.
    //!
    //! Generates a fresh CA + node cert pair in-memory each time. Same
    //! parameters the production `shade init-ca` / `shade issue-cert`
    //! use, just without writing PEM to disk.

    use rcgen::{
        BasicConstraints, CertificateParams, DistinguishedName, DnType, IsCa, KeyPair,
        KeyUsagePurpose, SanType,
    };
    use rustls::pki_types::{CertificateDer, PrivateKeyDer};

    #[allow(clippy::struct_field_names)]
    pub struct TestPki {
        pub ca_cert_der: CertificateDer<'static>,
        pub ca_kp_pem: String,
        pub ca_rcgen: rcgen::Certificate,
    }

    impl TestPki {
        pub fn new() -> Self {
            let kp = KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
            let mut params = CertificateParams::new(Vec::<String>::new()).unwrap();
            let mut dn = DistinguishedName::new();
            dn.push(DnType::CommonName, "Shade Test CA");
            params.distinguished_name = dn;
            params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
            params.key_usages = vec![
                KeyUsagePurpose::DigitalSignature,
                KeyUsagePurpose::KeyCertSign,
                KeyUsagePurpose::CrlSign,
            ];
            let cert = params.self_signed(&kp).unwrap();
            let der = CertificateDer::from(cert.der().to_vec());
            Self {
                ca_cert_der: der,
                ca_kp_pem: kp.serialize_pem(),
                ca_rcgen: cert,
            }
        }

        pub fn issue(&self, node_id: &str) -> NodeCert {
            // Re-parse the CA key from PEM so the rcgen Certificate +
            // KeyPair pair can be reused for signing.
            let ca_kp = KeyPair::from_pem(&self.ca_kp_pem).unwrap();

            let kp = KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
            let mut params = CertificateParams::new(vec![node_id.to_owned()]).unwrap();
            let mut dn = DistinguishedName::new();
            dn.push(DnType::CommonName, node_id);
            params.distinguished_name = dn;
            params.subject_alt_names =
                vec![SanType::DnsName(node_id.to_owned().try_into().unwrap())];
            params.key_usages = vec![
                KeyUsagePurpose::DigitalSignature,
                KeyUsagePurpose::KeyEncipherment,
            ];
            params.extended_key_usages = vec![
                rcgen::ExtendedKeyUsagePurpose::ServerAuth,
                rcgen::ExtendedKeyUsagePurpose::ClientAuth,
            ];
            let signed = params.signed_by(&kp, &self.ca_rcgen, &ca_kp).unwrap();
            let cert_der = CertificateDer::from(signed.der().to_vec());
            let key_bytes = kp.serialize_der();
            let key_der = PrivateKeyDer::Pkcs8(key_bytes.clone().into());
            NodeCert {
                cert_der,
                key_der,
                key_bytes,
            }
        }
    }

    pub struct NodeCert {
        pub cert_der: CertificateDer<'static>,
        pub key_der: PrivateKeyDer<'static>,
        pub key_bytes: Vec<u8>,
    }

    impl NodeCert {
        /// Make a cloned `(cert, key)` pair — `PrivateKeyDer` itself
        /// isn't `Clone`. Lets a single issued cert be used for both
        /// the server and client TLS configs of the same node in tests.
        #[must_use]
        pub fn pair(&self) -> (CertificateDer<'static>, PrivateKeyDer<'static>) {
            (
                self.cert_der.clone(),
                PrivateKeyDer::Pkcs8(self.key_bytes.clone().into()),
            )
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use test_pki::TestPki;

    #[test]
    fn cert_node_id_extracts_san_first() {
        let pki = TestPki::new();
        let node = pki.issue("shade-iad-01");
        assert_eq!(
            cert_node_id(&node.cert_der).as_deref(),
            Some("shade-iad-01")
        );
    }

    #[test]
    fn server_and_client_configs_build_with_matching_ca() {
        let pki = TestPki::new();
        let server_node = pki.issue("server-node");
        let client_node = pki.issue("client-node");
        let ca_bundle = vec![pki.ca_cert_der.clone()];
        let _server = server_config(
            ca_bundle.clone(),
            vec![server_node.cert_der],
            server_node.key_der,
        )
        .expect("server config");
        let _client = client_config(ca_bundle, vec![client_node.cert_der], client_node.key_der)
            .expect("client config");
    }

    #[test]
    fn empty_ca_bundle_is_rejected() {
        let pki = TestPki::new();
        let node = pki.issue("node");
        let err = server_config(Vec::new(), vec![node.cert_der], node.key_der).unwrap_err();
        assert!(matches!(err, TlsConfigError::EmptyCaBundle));
    }
}
