[package]
name = "shade-bin"
description = "Shade IRC bot daemon and shadectl CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[[bin]]
name = "shade"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
